### ISSUE TITLE
تبریک

### ISSUE THREAD

**Issue by Mehrnoush504** [AMK9978/NoroozVacation#1]
سلام
این که اومدی برنامه ی روزانتو اینجا نوشتی واقعا خیلی خوبه :)
اینطوری با انجام هرکدوم میزان پیشرفت و پیشرویه کار خودتو می بینی :)
کارت شبیه اسکرامه واقعا ایده ی جالبی به ذهنت رسید واقعا آفرین :)

**Comment by AMK9978** [comment]
سلام
ممنون خیلی لطف کردی:)
آره ایده جالبیه دوست داشتی خودتم امتحانش کن:)
ممنونم ازت
بازم بیا:)

**Comment by Mehrnoush504** [comment]
خواهش می کنم :)
باشه ممنون بابت پیشنهادت :)
